ARG  FROMIMAGE=cp.icr.io/cp/appc/ace:12.0.9.0-r1
FROM ${FROMIMAGE}

USER root

# RUN microdnf update && microdnf clean all

ENV LICENSE=accept
ENV MQSI_REGISTRY=/tmp/perms-work-dir/config
ENV MQSI_WORKPATH=/tmp/perms-work-dir/config

COPY *.bar /tmp
COPY startup.sh /usr/local/bin

RUN set -x && \
    chmod -R ugo+rwx /home/aceuser/ && \
    chmod 777 /usr/local/bin/startup.sh

USER 1001

WORKDIR  /home/aceuser  

ENTRYPOINT ["/usr/local/bin/startup.sh" ]